### PR TITLE
rename allChannelsActive to anyChannelsActive

### PR DESCRIPTION
**Pull request by ubbabeck**
Instead of requiring all channels to be active only one channel needs to be active in order to create invoices or payment attempts.

### CODE REVIEW

**Comment by kingonly** [comment]
This can't be trivial... We can't and shouldn't implement such logic do it with an LSP (it depends on the amount etc). If you want to ignore end end channels, maybe.

**Comment by kingonly** [comment]
Maybe, but I need to understand why are we changing the logic. If it's because Tor, we can add specific logic to Tor channels. We can't afford regressions and this is a sensitive code flow.

**Comment by yaslama** [comment]
> Maybe, but I need to understand why are we changing the logic.

Tor triggered the need, but if someone is connected to several lsps and one of them is offline, do we let him receive transactions through others?

**Comment by kingonly** [comment]
Not a question I want to answer now. Let's cross that bridge when we get there. For now, let's minimize the scope. In the future, we may expand it. But there are implications either way.

**Comment by ubbabeck** [comment]
Yes, this was added in order to be able create invoices/  receive payments if the client has an open channel to a node behind tor that is not reachable and also for unreachable channels in general. 

Will see if I can find an alternative in order to avoid closing *inactive channels* to non LSP nodes.

**Pull request closed without merging**
